manipulator:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: Manipulation2
  kinematics_solver_search_resolution: 0.0001
  kinematics_solver_timeout: 0.05
  position_only_ik: True
